language: node_js
node_js:
- 6
- 8
- lts/*
- node
env:
  global:
    secure: u/tf3OupAuoB8xPGivv0YNzg1RpwlxszGr9x6aUl7gEYGT5C0NJJzHtazGs5JXvvNDilukAc9c0AQsNEd+jmVfUL138O7n2kdZgYoTLSRGFz7C7V7kfFoYgPgv+/8zzqVCvsb/6hL0H6SNabqNv5RnvlanGF4BcMpsWO2xZB7L11kOUfPVP5PVF+xc5QJCRPWT6RUqFIOTVR2ajqi7igt9ZNetYiiG/O2/Xw0NLc3eYh9+oEKmz+ehfxj6r2+x4R0dDgen0h7QeqJP5eoHmmddDpcpcefThhac5C9bhkWyOY16Tg1dTULz8N55+cwtYE3GpVcebQJX3CeZGWjzJrH4XC8P9ov6Z/jP8UDFk+vZpXuzu7jeQLjjn5V9VfeO0J6V0yzhkk76eUO4gLQL4C6OicbGC1ivzHVncByEl7UWqC7NnieQLM7y7mZmQphkGjKpIoacrCJyaUpaH4HdGZR6s8ysUIfIDJapGdvSCTvuzbOQ2OM7+5pCJW75pwCuhhDtQLkYty/F/YkglZ2kye1d8D67aIv7GJAnmZUB7tuqRDTGJvGuSh7b2U/WsTQ03DsUSOppmgEbLkEFNAI0aPs1/Lb9OS4oy2Q97Sfg1yfZWVfVY4UlKFs5CyDBw6hy++8TpJU0aUaCTdnSnIwnBPh97bIjL4h8wRCN+myxiKRvE=
